apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx-deployment
  labels:
    app: argocd-nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: argocd-nginx
  template:
    metadata:
      labels:
        app: argocd-nginx
    spec:
      containers:
      - name: argocd-nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      - name: argocd-nginx-2
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080