apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx-deployment
  labels:
    app: argocd-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-nginx
  template:
    metadata:
      labels:
        app: argocd-nginx
    spec:
      containers:
      - name: argocd-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80